### ISSUE TITLE
Consolidate apache redirections

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/main-wp-website-deployment#21]
There are a number of redirections that are being used in the library domain.  These are the current ones:

```bash
[quinn@blue stage]$ for i in old.lib.ucdavis.edu lib.ucdavis.edu aeon.library.ucdavis.edu ; do host $i; done
old.lib.ucdavis.edu is an alias for basil.lib.ucdavis.edu.
basil.lib.ucdavis.edu has address 169.237.215.144
lib.ucdavis.edu has address 169.237.215.171
aeon.library.ucdavis.edu is an alias for bnl.library.ucdavis.edu.
bnl.library.ucdavis.edu has address 169.237.215.176

[quinn@blue stage]$ host 169.237.215.171
171.215.237.169.in-addr.arpa is an alias for 171.128-26.215.237.169.in-addr.arpa.
171.128-26.215.237.169.in-addr.arpa domain name pointer spoon.lib.ucdavis.edu.
```
If we'd like to consolidate these redirections, I have setup `file://router.ucdavis.edu/etc/httpd/conf.d/{old lib aeon}.conf to handle those redirects  They can be used with :

``` text
old.lib.ucdavis.edu CNAME router.library.ucdavis.edu
lib.ucdavis.edu CNAME router.library.ucdavis.edu
aeon.library.ucdavis.edu CNAME router.library.ucdavis.edu
```

One change to this is that `old.lib.ucdavis.edu` will only be available within the staff VPN as requested.

Added [diagram](https://docs.google.com/drawings/d/1nw_3TyurSa4UEb4Z_4ah-3_XTW7Po3O8c-WtRltKBRg/edit?usp=sharing) including the apache redirect.

**Comment by qjhart** [comment]
@NeilWeingarten you can pull an RT ticket and reference this issue.   I don't have access to the machines doing the redirection, so I'm not sure the rules I used are exactly the name.

 These changes don't have to happen, they are just suggestions.  IF they are updated, I don't know what the existing hosts `bnl.library.ucdavis.edu` and `spoon.lib.ucdavis.edu` would continue to be used for.

**Comment by NeilWeingarten** [comment]
Per James:

bnl.lib is our web hosting VM for sites other-than-production. We use it for things like slater.library.ucdavis.edu, aspace.lib.ucdavis.edu (archivesspace for speccoll), and several alias/redirect domains such as aeon.library.ucdavis.edu.

If you need a full list, let me know.

From your github link, spoon.lib.ucdavis.edu is our Windows domain controller for the LIB domain that does the authentication for kerberos accounts for VDI (the public kiosks in the libraries). It should be of no concern to you guys or your projects. Please let me know why this has come up?

Actually looking again at github I see the question about spoon is because lib.ucdavis.edu points to it. This is intentional since the name of the windows domain is lib.ucdavis.edu. It is not intended for use as a website and requires pointing to spoon for the domain to work properly. When this was done the websites were always [www.lib.ucdavis.edu](http://www.lib.ucdavis.edu/) or old.lib.ucdavis.edu or dev.lib.ucdavis.edu, lib.ucdavis.edu was never used for web and why, for http, it currently redirects to [www.library.ucdavis.edu](http://www.library.ucdavis.edu/).
